### PR TITLE
New login API endpoint

### PR DESCRIPTION
**Pull request by eykd**
This implements a JSON-based login API for django-cas-provider, with the following interaction:

Request a JSON "form" from the /v1/login endpoint:

```
$ http --verbose GET localhost:8111/v1/login/ api-key==f5139ee9a3ae45e38311bf6830edbadecd47f9f7 service==http://www.esvbible.org/cas/login/
GET /v1/login/?api-key=f5139ee9a3ae45e38311bf6830edbadecd47f9f7&service=http%3A%2F%2Fwww.esvbible.org%2Fcas%2Flogin%2F HTTP/1.1
Accept: */*
Host: localhost:8111


HTTP/1.0 200 OK
Cache-Control: proxy-revalidate, no-cache, must-revalidate
Content-Type: application/json; charset=utf-8
Pragma: no-cache
Vary: Cookie

{
    "email": null,
    "login_ticket": "LT-CzNj37JxtFkEUnudibGy6qm5hTrsX",
    "password": null,
    "service": "http://www.esvbible.org/cas/login/"
}
```

The client fills out the "form" w/ `email` and `password` fields, maintaining the `login_ticket` and `service` fields, and POSTs it to the same endpoint:

```
$ http --verbose POST localhost:8111/v1/login/ api-key==f5139ee9a3ae45e38311bf6830edbadecd47f9f7 login_
ticket=LT-CzNj37JxtFkEUnudibGy6qm5hTrsX password=mypassword email=deyk@crossway.org service=http://www.esvbible.org/cas/login/
POST /v1/login/?api-key=f5139ee9a3ae45e38311bf6830edbadecd47f9f7 HTTP/1.1
Accept: application/json
Content-Type: application/json
Host: localhost:8111

{
    "email": "deyk@crossway.org",
    "login_ticket": "LT-CzNj37JxtFkEUnudibGy6qm5hTrsX",
    "password": "mypassword",
    "service": "http://www.esvbible.org/cas/login/"
}

HTTP/1.0 302 FOUND
Cache-Control: proxy-revalidate, no-cache, must-revalidate
Content-Type: application/json; charset=utf-8
Location: http://www.esvbible.org/cas/login/?ticket=ST-3OMANly2VYnXQUtfP1cWTpz8Forgv
Pragma: no-cache
Vary: Cookie
```

The client follows the resulting redirect back to the CAS consumer service to verify the provided service ticket and obtain some sort of authenticated token.

### CODE REVIEW

**Comment by eykd** [comment]
@dwickwire This should be ready to go. Can you take a pass at reviewing it when you get a chance?

**Comment by dwickwire** [comment]
Hi David,

I'm not able to test this locally, I keep getting `ImportError: cannot import name api_login` when I start the server.  I have `feature/cas-login-api` checked out and up to date for django-cas-consumer and `feature/login-api` for federation, also checked out and up to date.  I'm trying to set it up on the ESVBible VM, should I be using the federation VM instead?  I noticed there's no port in the vagrant file for federation, so maybe I'm using the wrong VM there.

It looks like this is available on staging though.  I tried setting a password on staging using the host entry for oxgoad.  I used my FB login – here are a couple bugs I noticed.
- [ ] After I set password it redirected me to merge my accounts
- [ ] So after I merged, it asked for a confirmation password, I typed in an invalid one yet it merged the accounts successfully.
- [ ] Similarly I went to change my password next, and typed an incorrect old password and it still set my new password up.
- [ ] After all this federation kind of got locked up and I couldn't do any more testing.

**Comment by eykd** [comment]
Yes, please use the federation VM, which is set up to use `~/Crossway/django-cas-provider`. I'll get this staged today as well (it wasn't when you were testing).

The password stuff sounds like bugs, but unrelated to this PR. Can you open a separate issue for those?

**Comment by eykd** [comment]
This is staged, at least until the next time someone stages anything on esvbible. :) The deploy isn't set up to pull in a feature branch of a dependency, so it requires some manual rejiggering. Nobody touch anything!

**Comment by dwickwire** [comment]
Hm, I just tried going to my.crossway.org and got an Internal Server Error.  Looks like a) something is wrong, hah, and b) we should make sure the error pages are displayed for production too. 

I'll try to test this in the federation VM in the meantime.

**Comment by eykd** [comment]
I've addressed the problem on staging--the server simply needed to be restarted.

For testing on staging, you can use the API key `1e3ee86fcdf22169287c5b9dd5254ed91efb70d4`.

**Comment by dwickwire** [comment]
:+1:

**Pull request merged**
